### ISSUE TITLE
Delete Functionality

### ISSUE THREAD

**Issue by netfl0** [smartfile/django-sphinx-db#3]
https://code.djangoproject.com/browser/django/trunk/django/db/models/sql/compiler.py#L919

Model deletion has an SQL syntax issue i think, I am still working this out more details on this, just tracking the feature.

```
EntryIndex.objects.all().delete()

DatabaseError: (1064, "sphinxql: syntax error, unexpected IDENT, expecting ID near '`id` IN (20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1)'")

```

**Comment by btimby** [comment]
Sphinx seems to have trouble with the `` quotes used for identifiers.
They are inconsistent at best. Some places in their parser allow them,
some do not.

I wrote a forum post about this:

http://sphinxsearch.com/forum/view.html?id=9024

I think it might be worth opening a ticket with sphinx about it. They
could easily accept quoted identifiers by modifying their lexer.

**Comment by btimby** [comment]
I opened a bug report with Sphinx about inconsistent SQL support.

http://sphinxsearch.com/bugs/view.php?id=1150

I would like to see how important SQL compatibility is to Sphinx. The other option is to do more hacking on the SQLCompiler to produce compatible SQL, however, because the syntax is valid, I would think Sphinx should accept it as-is.

**Comment by btimby** [comment]
I committed two changes to the SphinxSQLCompiler. These changes produce SQL compatible with Sphinx.

https://github.com/btimby/django-sphinx-db/commit/86b8cb0aa7249c3d16b6f83fb50364a19409c7cd

These are by no means exhaustive, simply trimming leading and trailing parenthesis is likely to lead to bad syntax in queries that use multiple operations (AND and OR). However, such queries are not possible with SphinxSQL anyway since it does not support parenthesis.

Not quoting identifiers similarly can cause issues if column names are SQL reserved words. Again, this cannot be helped since Sphinx has issues with backticks.

The query in your initial report now executes properly.
